# This is a basic workflow to help you get started with Actions

name: Build and Deploy ASP .NET Core Chapter 12 to GitHub Pages

# Controls when the action will run. 
on:
  # trigger the workflow only when a push happens in Chapter 12
  push:
    branches: [ master ]
    paths:
    - ‘Chapter 12/Chapter_12_GitHubActions_Examples/**’

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # steps to build the application
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ‘5.0’
            
      - name: Publish app
        run: dotnet publish -c Release ‘./Chapter 12/Chapter_12_GitHubActions_Examples/Chapter12.csproj’
            
      - name: Save artifacts
        uses: actions/upload-artifact@v2
        with:
          name: myWASM
          path: ‘./Chapter 12/Chapter_12_GitHubActions_Examples/bin/Release/net5.0/publish/wwwroot’
      
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      # steps to deploy the application
      - uses: actions/checkout@v2
      
      - name: Create pages branch
        continue-on-error: true
        run: |
                git config --global user.name “lexeg”
                git config --global user.email “alexander.petrenko.develop@gmail.com”
                git checkout -B pages
                
      - name: Clear pages branch
        continue-on-error: true
        run: |
                git rm -rf .
                git commit --allow-empty -m “root commit”
                git push -f origin pages
                
      - name: Download build artifact
        uses: actions/download-artifact@v2
        with:
          name: myWASM
                
      - name: Commit changes
        run: |
            git add .
            git commit -m “publishing WASM”
            git push --set-upstream origin pages
